test: &default

  # Credentials for REST APIs
  client_id: AbEZcdtN73Q1xVADkQ655m-xTMHD3tqYBMGLPu3QjE1CAhAaJec_B5xLB9ChhRPPhx3wYzUDOekFWf4z
  client_secret: EC52r2MC6A4js8i5q6x3vJfltuEsInCl-u1NbfDXQF60B7KpLb5ZYLWHZPat5aZcHG0NakM9Qbv8CPUn

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
